# Generated by Django 4.2 on 2023-05-16 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_alter_userfollows_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
